//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoArrow.RouteFinding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoArrow.RouteFinding.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;locations type=&quot;CrossroadsOfDereth&quot; updated=&quot;633014139024843750&quot;&gt;
        ///    &lt;loc id=&quot;21&quot; name=&quot;Northern Al-Arqas Outpost&quot; type=&quot;Outpost&quot; NS=&quot;-28.2&quot; EW=&quot;13.9&quot;&gt;&lt;/loc&gt;
        ///    &lt;loc id=&quot;22&quot; name=&quot;Northern Al-Arqas Outpost&quot; type=&quot;Lifestone&quot; NS=&quot;-28.1&quot; EW=&quot;13.8&quot;&gt;&lt;/loc&gt;
        ///    &lt;loc id=&quot;23&quot; name=&quot;Western Al-Arqas Outpost&quot; type=&quot;Outpost&quot; NS=&quot;-31.3&quot; EW=&quot;10.7&quot;&gt;&lt;/loc&gt;
        ///    &lt;loc id=&quot;24&quot; name=&quot;Western Al-Arqas Outpost&quot; type=&quot;Lifestone&quot; NS=&quot;-31.2&quot; EW=&quot;10.8&quot;&gt;&lt;/loc&gt;
        ///    &lt;loc id=&quot;25&quot; name=&quot;Al- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocationsDatabase {
            get {
                return ResourceManager.GetString("LocationsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;mapRegions&gt;
        ///  &lt;innerPoly name=&quot;Marescent Plateau&quot;&gt;
        ///    &lt;coords NS=&quot;54.2&quot; EW=&quot;-78.3&quot; /&gt;
        ///    &lt;coords NS=&quot;49.2&quot; EW=&quot;-83.1&quot; /&gt;
        ///    &lt;coords NS=&quot;42.8&quot; EW=&quot;-82.8&quot; /&gt;
        ///    &lt;coords NS=&quot;42.1&quot; EW=&quot;-78.6&quot; /&gt;
        ///    &lt;coords NS=&quot;42.1&quot; EW=&quot;-74.3&quot; /&gt;
        ///    &lt;coords NS=&quot;44.3&quot; EW=&quot;-74.5&quot; /&gt;
        ///    &lt;coords NS=&quot;44.6&quot; EW=&quot;-73.5&quot; /&gt;
        ///    &lt;coords NS=&quot;43.2&quot; EW=&quot;-73.0&quot; /&gt;
        ///    &lt;coords NS=&quot;48.3&quot; EW=&quot;-69.6&quot; /&gt;
        ///    &lt;coords NS=&quot;48.8&quot; EW=&quot;-73.2&quot; /&gt;
        ///    &lt;coords NS=&quot;50.5&quot; EW=&quot;-71.5&quot; /&gt;
        ///    &lt;coords [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapRegions {
            get {
                return ResourceManager.GetString("MapRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;portalDevices&gt;
        ///  &lt;device icon=&quot;06003642&quot; name=&quot;Black Spawn Den Portal Device&quot;&gt;
        ///    &lt;destination NS=&quot;13.72&quot; EW=&quot;-79.84&quot; name=&quot;BSD Device to Northern Dires&quot; /&gt;
        ///    &lt;destination NS=&quot;-59.97&quot; EW=&quot;-57.72&quot; name=&quot;BSD Device to Obsidian Plain&quot; /&gt;
        ///    &lt;destination NS=&quot;-56.7&quot; EW=&quot;-86.0&quot; name=&quot;BSD Device to Western Dires&quot; /&gt;
        ///    &lt;description&gt;
        ///      Black Spawn Den Portal Device
        ///
        ///      Goes to one of the three Black Spawn Dens:
        ///      Northern Dires BSD (13.7N, 79.8W)
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PortalDevices {
            get {
                return ResourceManager.GetString("PortalDevices", resourceCulture);
            }
        }
    }
}
